### ISSUE TITLE
Rename IStorageProperties<T> to IStorageProperty<T>

### ISSUE THREAD

**Issue by d2dyno1** [Arlodotexe/OwlCore.Storage#17]
The interface `IStorageProperties<T>` represents a single storage property, and thus should be renamed to `IStorageProperty<T>`

**Comment by Arlodotexe** [comment]
We'll move forward with renaming `IStorageProperties<T>` to `IStorageProperty<T>`, since this is a single object returned by an async method.

@d2dyno1 Please file a separate issue for renaming `IAddressable`, it needs to be discussed more first.
