### ISSUE TITLE
Copy/Move fast paths not used when casting to interface

### ISSUE THREAD

**Issue by Arlodotexe** [Arlodotexe/OwlCore.Storage#20]
I noticed that for the interface check using the generic `T`:
https://github.com/Arlodotexe/OwlCore.Storage/blob/8baab6c92a9dd7195ffc8ad0b098d0fd1879c929/src/Extensions/CopyAndMoveExtensions.cs#L25

When `T` is declared as an interface instead of an implementation, this type check always fails and the fastpath for the specific `T fileToCopy` implementation is not selected. 

Unless you explicitly provide the type for the file to copy or move (not the interface), you'll always get the slower fallback code path. That breaks fastpaths unless you explicitly provide the type you meant, and that is slowing down some inbox tooling by avoiding fastpaths.

Might need to expose the generic parameter in more places if we want generic fastpaths to work 100% of the time. 

This only affects copy/move operations for now and will still work as expected, but it's still something for consumers to keep in mind in the meantime.

**Comment by yoshiask** [comment]
It might be useful to use [item.GetType().IsAssignableFrom(typeof(T))](https://learn.microsoft.com/en-us/dotnet/api/system.type.isassignablefrom?view=netstandard-2.0). I'm fairly certain this would have the desired behavior.

**Comment by Arlodotexe** [comment]
> It might be useful to use [item.GetType().IsAssignableFrom(typeof(T))](https://learn.microsoft.com/en-us/dotnet/api/system.type.isassignablefrom?view=netstandard-2.0). I'm fairly certain this would have the desired behavior.

That gives us a "yes" or "no" but doesn't give us a way to actually call into the instance.

**Comment by Arlodotexe** [comment]
Implementations might be able to avoid this error by implementing `IFastFileCopy<T>` and `IFastFileMove<T>` with the `IFile` interface, and do a type check for the implementations they do support.

**Comment by sylveon** [comment]
> > It might be useful to use [item.GetType().IsAssignableFrom(typeof(T))](https://learn.microsoft.com/en-us/dotnet/api/system.type.isassignablefrom?view=netstandard-2.0). I'm fairly certain this would have the desired behavior.
> 
> That gives us a "yes" or "no" but doesn't give us a way to actually call into the instance. We need that.

If this method says yes then a cast works.

**Comment by Arlodotexe** [comment]
@yoshiask @sylveon I gave this a try under our unit tests and no luck.

Retried with all combinations and variations and still no luck.  

![image](https://github.com/Arlodotexe/OwlCore.Storage/assets/9384894/077dd67d-0af3-45ca-a23e-6b06bacc2fcc)

Seems like I'm missing something here.

**Comment by Arlodotexe** [comment]
Revisiting the PR where we added the generics, the rational for why we used generics here isn't documented -> https://github.com/Arlodotexe/OwlCore.Storage/issues/9

Maybe we look at removing the generics entirely and using a single method that is provided an `IFile` instead of having overloads for each supported type.

**Comment by yoshiask** [comment]
For this to work, wouldn't we need co/contravariance (I'm not CSCE, I forget which) on the IFast interfaces?

**Comment by Arlodotexe** [comment]
Regarding covariance/contravariance -- with some guidance from Bing:
> If the `IFast...<T>` interfaces are expected to handle a type `T` and its subtypes interchangeably, then covariance would be needed. On the other hand, if the `IFast...<T>` interfaces are expected to handle a type `T` and its supertypes interchangeably, then contravariance would be needed.
> [...]
> In the case you’ve described, where `IFast...<T>` takes a `T` that is an implementation of `IFile`, and `IFile` can be derived as `SystemFile`, `WindowsStorageFile`, `HttpFile`, etc., you would likely want to use covariance.
> 
> Here’s why: With covariance, if `T` is a subtype of `IFile` (like `SystemFile`, `WindowsStorageFile`, or `HttpFile`), then `IFast...<T>` would be able to handle `T` and its subtypes interchangeably. This means you could use an `IFast...<SystemFile>`, for example, wherever an `IFast...<IFile>` is expected.
> [...]
> However, please note that whether you can actually make `IFast...<T>` covariant depends on the specific language and its type system. Some languages might not support covariance, or might only support it under certain conditions. For example, in C#, you can only make an interface covariant if `T` is only used in output positions (like return values) and not in input positions (like method parameters).

Noting that we're currently using contravariance:
https://github.com/Arlodotexe/OwlCore.Storage/blob/8baab6c92a9dd7195ffc8ad0b098d0fd1879c929/src/Extensions/IFastFileCopy.cs#L11

Changing this from `in` to `out` gives the error message:
```
Covariant type parameter 'T' is used in contravariant position. Parameter must be input-safe.
```

@yoshiask To answer your question, covariance would fix this, but C# doesn't allow it for input parameters.

**Comment by Arlodotexe** [comment]
This solution provides implementations with a way to override the copy path so that it can handle known types.

However, it doesn't provide implementations with a way to access the _fallback_ copy path for unknown types. This is provided by the extension method, and is meant to run if the folder doesn't pass the check for the provided file type. However, since generics have fallen short and are no longer used, this must be done a different way. 

Considering the use cases here, we have two options:
1. Give consumers access to a method for the fallback copy/move to call. One that doesn't reroute the call from the interface extension to the implementation, but instead calls the fallback directly or otherwise skips it.
    - Requires defining another Copy/Move extension method or an overload on the existing one, which may be confusing for both those looking to copy/move and those looking to implement copy/move.
    - This method means calling into the fast/direct interface will support types other than those explicitly handled. Not needed, but nice to have. Maybe an anti-pattern?
    - No way for the interface to self-explain how this should work.
  
2. Have the consumer define or otherwise signal when a type is or isn't supported. Simply skip the call to the extension interface and go directly to the default fallback copy/move operation.
    - Lib consumers will need to avoid calling folder instances cast to the extension interfaces, as it will call the implementation directly and not have a fallback path for unhandled file implementation types.
    - Could be done either by:
      - Placing a list of types on the extension interfaces and have the implementation populate it.
        - Requires changing the API surface.
        - Requires a throw to be declared in the implementation when a file isn't a handled type. 
      - Throwing and catching a custom exception
        - Since a throw will need to be declared in the implementation regardless, we could make it part of spec to have the extension interfaces throw a custom exception to indicate that the provided file argument isn't a handled type.
        - Doesn't require adding, removing or changing the existing API surface.
    - Still no way for the interface to self-explain how this is meant to work.

Given the options, I'm leaning towards **Throwing and catching a custom exception**. Thoughts?

**Comment by Arlodotexe** [comment]
A week on and I've gotten a bit of feedback from the community. One bit of feedback in particular from @yoshiask highlights the flexibility offered by option 1:
> Some implementations might need more information than just a type to determine if a fast copy/move is available. For example, a fast path is available for moving items within the same ZIP archive, but not across two different archives

I'll move forward with Option 1 as planned, then.
