### ISSUE TITLE
Expose System.IO properties directly in SystemFile

### ISSUE THREAD

**Issue by HEIC-to-JPEG-Dev** [Arlodotexe/OwlCore.Storage#27]
**Issue**
SystemFile assumes it's existance, and has limited use (issue #26) and without core properties (Attributes, Dates, Exists, etc) is slow and unusable.

**Reason**
A file's state is not static, it can change outside of the app at any time.

**Proposal**
The constructor of SystemFile should not assume or enforce anything. It shoudl simply return an object (or null).
The developer can then check for Exists, Attributes, and use the path manipulation properties even on none-existance files.

For example: systemFile.Filename or systemFile.Extention - these properties are very useful for path manipulation and are currently absent and also would not be available if the constructor of systemFile rejects none-existant files.

**Comment by Arlodotexe** [comment]
> SystemFile assumes it's existance...The constructor of SystemFile should not assume or enforce anything. It shoudl simply return an object (or null).

This is on purpose. See [this comment](https://github.com/Arlodotexe/OwlCore.Storage/issues/26#issuecomment-1492316984).

> For example: systemFile.Filename or systemFile.Extention

These are exposed via on `IStorable.Name`. Use [`System.IO.Path.GetExtension`](https://learn.microsoft.com/en-us/dotnet/api/system.io.path.getextension?view=net-8.0) to get the extension from the name.

> The developer can then check for Exists, Attributes, and use the path manipulation properties even on none-existance files.

In #23, we're working on standardizing properties so properties from implementation can be consumed using a single common API.

It seems like you just need access to the underlying System.IO APIs given an instance of `SystemFile` or `SystemFolder`. We try to provide this functionality in every implementation we make, so there's no need to add all these things to `SystemFile` directly. 

I would recommend using the `SystemFile.Path` in combination with `System.IO` APIs such as [`FileInfo`](https://learn.microsoft.com/en-us/dotnet/api/system.io.fileinfo?view=net-8.0).

For example,
```cs
var file = new SystemFile("C:\file.txt");
var fileInfo = new FileInfo(file.Path);

// Access the data you need
var w = fileInfo.Attributes;
var x = fileInfo.CreationTime;
var y = fileInfo.Exists;
var z = fileInfo.Length;
```
