### ISSUE TITLE
Better parameter validation for SystemFile ctor

### ISSUE THREAD

**Issue by HEIC-to-JPEG-Dev** [Arlodotexe/OwlCore.Storage#28]
**Issue**
Exception raised is a FileNotFoundException, this is incorrect. 

**Reason**
The exception will be raised for many different reasons, for example, an invalid path, null, empty, or the user does not have permissions

**Proposal**
Either fire the correct exception, remove exceptions (issue #24), or remove the check in its entirety and use properties (see issue #27)

**Comment by Arlodotexe** [comment]
`File.Exists()` should throw the correctly if the user doesn't have permission to access the file.

However, according to the [docs](https://learn.microsoft.com/en-us/dotnet/api/system.io.file.exists?view=net-8.0#remarks):
> The [Exists](https://learn.microsoft.com/en-us/dotnet/api/system.io.file.exists?view=net-8.0) method returns false if any error occurs while trying to determine if the specified file exists. This can occur in situations that raise exceptions such as passing a file name with invalid characters or too many characters, a failing or missing disk, or if the caller does not have permission to read the file.

So there's definitely improvements to make for input validation on `SystemFile`'s constructor. We should at least be checking [`Path.GetInvalidPathChars`](https://learn.microsoft.com/en-us/dotnet/api/system.io.path.getinvalidpathchars?view=net-8.0) to make sure the format is correct. Any other ideas?

Adding info from #24:
> We took cues from what System.IO and Windows.Storage when deciding when to use exceptions.
> 
> If calling `File.Exists` here creates an overhead problem we can measure, we can see about removing it. Otherwise, it's one-time parameter validation. See https://github.com/Arlodotexe/OwlCore.Storage/issues/26#issuecomment-1492316984
> 
> Generally, we use exceptions to indicate undesirable states caused by invalid data. We also use exceptions to indicate when a file/folder does not exist on methods where the intent of the method isn't "check if it exists" (same as .NET).

**Comment by HEIC-to-JPEG-Dev** [comment]
In my library I have a path validation static helper that can be used within the storage classes and also by any code to validate before passing paramaters. 

I agree that at minimum it should validate the path and return a different error, and also for access violations.
