### ISSUE TITLE
SystemFile should have FileInfo constructor

### ISSUE THREAD

**Issue by HEIC-to-JPEG-Dev** [Arlodotexe/OwlCore.Storage#29]
**Issue**
SystemFile currently uses a string for the path. This is inconsistent with SystemFolder and also inefficient.

**Reason**
Disk IO related tasks need to be as fast as possible.
You do not know where the initial file data came from. You assume a path, but the developer may already have a FileInfo object
If the developer has a FileInfo object (or FilesystemInfos object), discarding the data from that object is wasteful.

**Proposal**
Two contructors, one for path, one for FileInfo.

**Comment by Arlodotexe** [comment]
Odd, thought we had this in both `SystemFile` and `SystemFolder`, looks like `SystemFile` is missing it. Let's add it!

**Comment by HEIC-to-JPEG-Dev** [comment]
Perfect, also if you're adding it you can leverage the optimizations in FileInfo for checking to see if the file exists and for returning any base properties.
