### ISSUE TITLE
Incorrect folder check in SystemFolderWatcher

### ISSUE THREAD

**Issue by yoshiask** [Arlodotexe/OwlCore.Storage#3]
# The problem
https://github.com/Arlodotexe/OwlCore.Storage/blob/7efe3384a9d6de24ad4f0965cd3aea4cc8214ad5/src/SystemIO/SystemFolderWatcher.cs#L114
This method appears to check if a given path is a folder by stripping any trailing slashes and comparing that to `Path.GetDirectoryName(path)`. Because `Path.GetDirectoryName` returns the path to the parent directory, this check will sometimes fail even for folders. For example:
![image](https://user-images.githubusercontent.com/7549325/188366699-303fd574-3486-467f-88ee-01292885bd11.png)

Note this test will pass if the path does have a trailing slash, since in that case `Path.GetDirectoryName` will effectively return the root of an arbitrary subdirectory in the given path, which of course is always the original path.

# The solution
The only reliable way to check if a path is folder is by asking the filesystem, calling `Directory.Exists(path)` like this:
https://github.com/Arlodotexe/OwlCore.Storage/blob/7efe3384a9d6de24ad4f0965cd3aea4cc8214ad5/src/SystemIO/SystemFolder.cs#L236

# Remarks
The `IsFile` check has a similar issue; it will return `true` for both files and directory paths without trailing slashes.

**Comment by Arlodotexe** [comment]
Good catch! Let's get this fixed.
