### ISSUE TITLE
SystemFile Cached Properties and Refresh

### ISSUE THREAD

**Issue by HEIC-to-JPEG-Dev** [Arlodotexe/OwlCore.Storage#30]
**Issue**
There are currently no File properties

**Proposal**
Properties have yet to be implemented, but when they are, the following principles should be adopted.

1. They are cached when possible;  
2. Implement Refresh and RefreshAsync to populate the core properties in a single method (same as FileInfo)
3. For properties that are not cached and require disk IO (Exists, Attributes, Dates, etc.) they should call Refresh or RefreshAsync to allow multiple properties to be updated in a single call

**Options**
SystemFile is a "live" view of the file. In this scenario, any call to a property will get the latest update from disk (Attributes, Exists, etc.); this will require those properties to be Async.

**Options**
Two properties of each type where disk IO is required, for example "Exists" and "ExistsAsync", one uses cached results, one is direct to disk. this gives the developer the option to choose.

**Comment by Arlodotexe** [comment]
This storage abstraction aims to create a single API surface that _every_ file system can implement.
