### ISSUE TITLE
SystemFile Path Validation

### ISSUE THREAD

**Issue by HEIC-to-JPEG-Dev** [Arlodotexe/OwlCore.Storage#31]
**Issue**
The path is not validated before use. 

**Proposal**
Validate the path before attempting to use it
Potential to put this in the constructor or use a property "IsPathValid" or "IsValid" - which could perform multiple checks and return different reasons why the object may not be valid, for example: path invalid, user access permissions, disk no longer available.

**Comment by Arlodotexe** [comment]
@HEIC-to-JPEG-Dev The path is validated here:

https://github.com/Arlodotexe/OwlCore.Storage/blob/main/src/SystemIO/SystemFile.cs#L18
