### ISSUE TITLE
Long Path Support

### ISSUE THREAD

**Issue by HEIC-to-JPEG-Dev** [Arlodotexe/OwlCore.Storage#32]
**Issue**
Owlcore.Storage does not support long paths [>260 characters]

**Reason**
The managed code in .net is being used in it's basic form; under the covers, the wide Win32 API is being used, however, the correct parameters for long paths is not being set.

**Proposal**
Implement internal (the the class) long path support.
Retain external (public properties of the class) use of simple strings.

**Comment by Arlodotexe** [comment]
@HEIC-to-JPEG-Dev I though LongPath support was enabled at the OS level 🤔 

Can you tell me more about what this might look like? What class is this for?

**Comment by HEIC-to-JPEG-Dev** [comment]
.Net supports long filenames but doesn't implement it by default, neither do the underlying Win32 API's (even file explorer doesn't do it)

Prefix paths with \\?\ when passing the path to any methods.

Windows 10 supports long paths but's in an opt-in via the registry, an no user will do that.

**Comment by Arlodotexe** [comment]
> Prefix paths with \?\ when passing the path to any methods.

The user provides the path in the constructor for `SystemFile` and `SystemFolder`, the consumer can add the prefix before passing it in if they feel it's needed in their application. 

Baking in support for this means prefixing the path before passing to System.IO, but System.IO may return that changed path. Support for long-length paths should be done by the running OS and .NET runtime, not us.
