### ISSUE TITLE
SystemFile Properties and ReadOnlySpan

### ISSUE THREAD

**Issue by HEIC-to-JPEG-Dev** [Arlodotexe/OwlCore.Storage#33]
**Issue**
Properties are being set in the constructor.

**Reason**
Properties that can be defined on access should be used. Specifically "Name" uses "System.IO.Path.GetFileName(path);" and while this is not a performance issue, it does allocation a string which may not be used.
When creating many SystemFile objects, this will be additional load that the constructor does not need.

**Proposal**
The property should be a "get" only and self caching (or nul coalescing).
An additional propert should be available that uses ReadOnlySpan, this avoids the allocation of a string. If this is implemented, it could be used in the constructor as it has no string allocation.

**Comment by Arlodotexe** [comment]
Good suggestion, we can do this. PRs are welcome!
