### ISSUE TITLE
Use of File.Exists can lead to TOCTOU bugs

### ISSUE THREAD

**Issue by sylveon** [Arlodotexe/OwlCore.Storage#37]
File.Exists is used in various places in the code before performing an action. These checks should be removed and the operation attempted directly, as they are a source of TOCTOU bugs (which can potentially be security vulnerabilities).

**Comment by Arlodotexe** [comment]
> In [software development](https://en.wikipedia.org/wiki/Software_development), time-of-check to time-of-use (TOCTOU, TOCTTOU or TOC/TOU) is a class of [software bugs](https://en.wikipedia.org/wiki/Software_bug) caused by a [race condition](https://en.wikipedia.org/wiki/Race_condition) involving the checking of the state of a part of a system (such as a security credential) and the use of the results of that check.

If you're referring to #28, TOCTOU bugs require both checking and accessing. We are only checking, not accessing. 

Could you provide examples of where this is used in our codebase that might cause a check/access race condition?

**Comment by sylveon** [comment]
> We are only checking, not accessing.

Yes, but then the user does later access based on those checks.

**Comment by Arlodotexe** [comment]
I'm not sure i understand the concern. We do this in the constructor so that check/access race conditions _can't_ happen. 

Our API dictates the resource should exist with reasonable confidence on construction, so that when you try to access the file and use the object, it doesn't throw.
