### ISSUE TITLE
Remove default value for accessMode flag in IFile

### ISSUE THREAD

**Issue by d2dyno1** [Arlodotexe/OwlCore.Storage#42]
## The problem
The current `IFile` interface contains a function `OpenStreamAsync()` which opens the file in read-only mode.
```cs
public Task<Stream> OpenStreamAsync(FileAccess accessMode = FileAccess.Read, CancellationToken cancellationToken = default);
```
This might cause erroneous behavior when trying to open a file in a read-write mode without an indication of it.

## The solution
Remove the default flag for the `accessMode` parameter:
```cs
public Task<Stream> OpenStreamAsync(FileAccess accessMode, CancellationToken cancellationToken = default);
```
and let the user create additional extension methods (`OpenReadAsync()`, `OpenWriteAsync()`) for opening the file at their own discretion.

**Comment by Arlodotexe** [comment]
We can for sure create extension methods for `OpenReadAsync` and `OpenWriteAsync`. 

As for removing the default value here, after thumbing through the official dotnet APIs (e.g. [`FileStream`](https://learn.microsoft.com/en-us/dotnet/api/system.io.filestream?view=net-8.0), [`File.Open`](https://learn.microsoft.com/en-us/dotnet/api/system.io.file.open?view=net-8.0#system-io-file-open(system-string-system-io-filemode-system-io-fileaccess)), etc), I'm inclined to agree.

This will be a broad-impact breaking change and will affect both implementors and consumers everywhere `IFile` is used. We should have a more discussion on this before committing to it, I'd like to hear what others think.
