### ISSUE TITLE
Rename IFast.. interfaces

### ISSUE THREAD

**Issue by d2dyno1** [Arlodotexe/OwlCore.Storage#46]
## Motivation
Currently, there are so-called "fast-path" interfaces that omit base operations, if an implementation supports a more efficient alternative. The prefix "Fast" is not effective in this measure since the operation can still take more time than perceived "fast".

```cs
public interface IFastFileCopy<in T> : IModifiableFolder where T : IFile
```
```cs
public interface IFastGetFirstByName : IFolder
```
copying or enumerating large collections is not fast by any means.

## Proposal
I propose to rename all interfaces prefixed with "Fast" to "Direct" as it better reflects the intentions of such interfaces. They are meant to provide an alternative way to **directly** access a certain functionality, not necessarily fast.

```cs
public interface IDirectFileCopy<in T> : IModifiableFolder where T : IFile
```
```cs
public interface IDirectGetFirstByName : IFolder
```

**Comment by Arlodotexe** [comment]
Thanks for the feedback, this is worth discussing.

### Current rational
In this abstract, we employ a trick to support certain operations that don't require explicit implementation to perform. For example, if you need to find the root parent of an item, we can either recursively call `GetParentAsync`, or if it's supported, we can delegate to the `IFastGetRoot` interface instead. These act as fastpaths for the interfaces, and shouldn't be implemented if the underlying implementation is slower.

### Should we?
I could see this being conceptually reframed as "manual" and "direct" operations, but the new naming underscores the reason we did this in the first place just a bit.

I'm 50/50 on this, and would like to see more discussion from the community on what they think.

**Comment by Arlodotexe** [comment]
After implementing `IGetCid` in OwlCore.Kubo using a similar pattern (in [this](https://github.com/Arlodotexe/OwlCore.Kubo/commit/6e6dd328a49c3712b462e7edffd9fca24e2d9d74) commit), I'm thinking we should remove any reference to "Fast" or "Direct" entirely, and instead write the names as `IMethodName`, without `Async` at the end. For example, instead of `IFastGetRoot` or `IFastGetFirstByName`, the interface would be `IGetRoot` or `IGetFirstByName`.

**Comment by d2dyno1** [comment]
Good idea! However, there's one problem - how are we going to differentiate between those interfaces and know which ones refer to the file system structure and which are completely irrelevant?

**Comment by Arlodotexe** [comment]
> Good idea! However, there's one problem - how are we going to differentiate between those interfaces and know which ones refer to the file system structure and which are completely irrelevant?

We don't need to, it's implied by being under the `OwlCore.Storage` namespace.

**Comment by Arlodotexe** [comment]
@d2dyno1 Do you have any remaining issues with the proposed naming scheme?

**Comment by Arlodotexe** [comment]
We'll move forward with the proposed naming scheme in 0.10.0
